# Generated by Django 2.1.1 on 2019-05-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20190518_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLocation',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Denton Hills', 'Denton Hills'), ('Wright Valley', 'Wright Valley'), (
                    'Taylor Valley', 'Taylor Valley'), ('Victoria Valley', 'Victoria Valley'), ('McKelvey Valley', 'McKelvey Valley')], max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='pdfreport',
            name='location',
        ),
        migrations.AddField(
            model_name='pdfreport',
            name='location',
            field=models.ManyToManyField(
                to='map.ReportLocation', verbose_name='list of locations'),
        ),
    ]
