# Generated by Django 2.1.1 on 2019-05-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20190520_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfreport',
            name='event_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reportlocation',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
